cameras:
- camera_id: cam-02
  site_id: 'site ID '
  name: 'camera công ty '
  description: 'Team AI '
  rtsp_url: rtsp://root:Admin!123@10.1.1.174:554/cam/realmonitor?channel=1&subtype=0
  enabled: true
  codec: h265
  fps_sample: 6
  imgsz: 640
  conf_fire: 0.7
  conf_smoke: 0.7
  conf_other: 0.4
  window_size: 10
  fire_hits: 3
  smoke_hits: 3
  cooldown_sec: 60
